import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

exoplanetDF = pd.read_csv("data/scored_exoplanets.csv")

plt.hist(exoplanetDF['pl_orbsmax'], bins=np.linspace(0, 1.5, 31), color='blue', edgecolor='black')
plt.xlabel('Orbital Distance [AU]')
plt.ylabel('Number of Planets')
plt.title('Orbital Distance Distribution')
plt.savefig('results/pl_orbsmax_hist.png')
plt.close()

plt.hist(exoplanetDF['pl_rade'], bins=np.linspace(0, 20, 31), color='red', edgecolor='black')
plt.xlabel('Planet Radius [Earth Radii]')
plt.ylabel('Number of Planets')
plt.title('Planet Radius Distribution')
plt.savefig('results/pl_rade_hist.png')
plt.close()

plt.hist(exoplanetDF['pl_bmasse'], bins=np.linspace(0, 1000, 31), color='green', edgecolor='black')
plt.xlabel('Planet Mass [Earth Masses]')
plt.ylabel('Number of Planets')
plt.title('Planet Mass Distribution')
plt.savefig('results/pl_masse_hist.png')
plt.close()

plt.hist(exoplanetDF['pl_dens'], bins=np.linspace(0, 30, 31), color='yellow', edgecolor='black')
plt.xlabel('Planet Density [g/cm^3]')
plt.ylabel('Number of Planets')
plt.title('Planet Density Distribution')
plt.savefig('results/pl_dens_hist.png')
plt.close()

plt.hist(exoplanetDF['pl_orbeccen'], bins=np.linspace(0, 1, 31), color='orange', edgecolor='black')
plt.xlabel('Planet Eccentricity [Eccentricity]')
plt.ylabel('Number of Planets')
plt.title('Planet Eccentricity Distribution')
plt.savefig('results/pl_orbeccen_hist.png')
plt.close()

plt.hist(exoplanetDF['pl_insol'], bins=np.linspace(0, 4000, 31), color='purple', edgecolor='black')
plt.xlabel('Planet Insolation Flux [Earth Flux]')
plt.ylabel('Number of Planets')
plt.title('Planet Insolation Flux Distribution')
plt.savefig('results/pl_insol_hist.png')
plt.close()

plt.hist(exoplanetDF['pl_eqt'], bins=np.linspace(0, 2740, 31), color='pink', edgecolor='black')
plt.xlabel('Planet Equilibrium Temperature [K]')
plt.ylabel('Number of Planets')
plt.title('Planet Equilibrium Temperature Distribution')
plt.savefig('results/pl_eqt_hist.png')
plt.close()

plt.hist(exoplanetDF['sy_dist'], bins=np.linspace(0, 3461, 31), color='gray', edgecolor='black')
plt.xlabel('Planet Distance from Earth [PC]')
plt.ylabel('Number of Planets')
plt.title('Planet Distance from Earth Distribution')
plt.savefig('results/sy_dist_hist.png')
plt.close()

plt.hist(exoplanetDF['score'], bins=np.linspace(0, 100, 31), color='white', edgecolor='black')
plt.xlabel('Planet Habitability Score]')
plt.ylabel('Number of Planets')
plt.title('Planet Habitability Score Distribution')
plt.savefig('results/score_hist.png')
plt.close()

print("Planet's distance from host star in AU:")
print("Mean: ", exoplanetDF["pl_orbsmax"].mean())
print("Median: ", exoplanetDF["pl_orbsmax"].median())
print("Mininmum: ", exoplanetDF["pl_orbsmax"].min())
print("Maximum: ", exoplanetDF["pl_orbsmax"].max())
print()

print("Planet's radius in Earth radii")
print("Mean: ", exoplanetDF["pl_rade"].mean())
print("Median: ", exoplanetDF["pl_rade"].median())
print("Mininmum: ", exoplanetDF["pl_rade"].min())
print("Maximum: ", exoplanetDF["pl_rade"].max())
print()

print("Planet's mass in Earth massses")
print("Mean: ", exoplanetDF["pl_bmasse"].mean())
print("Median: ", exoplanetDF["pl_bmasse"].median())
print("Mininmum: ", exoplanetDF["pl_bmasse"].min())
print("Maximum: ", exoplanetDF["pl_bmasse"].max())
print()

print("Planet's density in g/cm^3")
print("Mean: ", exoplanetDF["pl_dens"].mean())
print("Median: ", exoplanetDF["pl_dens"].median())
print("Mininmum: ", exoplanetDF["pl_dens"].min())
print("Maximum: ", exoplanetDF["pl_dens"].max())
print()

print("Planet's orbital eccentricity")
print("Mean: ", exoplanetDF["pl_orbeccen"].mean())
print("Median: ", exoplanetDF["pl_orbeccen"].median())
print("Mininmum: ", exoplanetDF["pl_orbeccen"].min())
print("Maximum: ", exoplanetDF["pl_orbeccen"].max())
print()

print("Planet's insolation flux")
print("Mean: ", exoplanetDF["pl_insol"].mean())
print("Median: ", exoplanetDF["pl_insol"].median())
print("Mininmum: ", exoplanetDF["pl_insol"].min())
print("Maximum: ", exoplanetDF["pl_insol"].max())
print()

print("Planet's equilibrium temperature")
print("Mean: ", exoplanetDF["pl_eqt"].mean())
print("Median: ", exoplanetDF["pl_eqt"].median())
print("Mininmum: ", exoplanetDF["pl_eqt"].min())
print("Maximum: ", exoplanetDF["pl_eqt"].max())
print()

print("Planet's distance from Earth")
print("Mean: ", exoplanetDF["sy_dist"].mean())
print("Median: ", exoplanetDF["sy_dist"].median())
print("Mininmum: ", exoplanetDF["sy_dist"].min())
print("Maximum: ", exoplanetDF["sy_dist"].max())
print()

print("Planet's habitabiltiy score")
print("Mean: ", exoplanetDF["score"].mean())
print("Median: ", exoplanetDF["score"].median())
print("Mininmum: ", exoplanetDF["score"].min())
print("Maximum: ", exoplanetDF["score"].max())
print()